project:
  type: website

website:
  title: "Math378FinalProject"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - eda.qmd
      - model.qmd

format:
  html:
    css: styles.css
    includes:
      in-header: header.html
    toc: true

editor: visual
