---
title: "Penguins EDA"
format:
  html:
    code-fold: true
    includes:
      in-header: |
        <link rel="stylesheet" href="styles.css">
---

## Penguin Size and Mass by Sex and Species

```{r}
suppressPackageStartupMessages({
  library(palmerpenguins)
  library(dplyr)
  library(dbplyr)
  library(ggplot2)
})

#con <- DBI::dbConnect(
  #duckdb::duckdb(), 
  #dbdir = "my-db.duckdb"
  #)
#df <- dplyr::tbl(con, "penguins")
df <- palmerpenguins::penguins
```

```{r}
df %>%
  group_by(species, sex) %>%
  summarise(
    avg_bill_length = mean(bill_length_mm, na.rm = TRUE),
    avg_flipper_length = mean(flipper_length_mm, na.rm = TRUE),
    avg_body_mass = mean(body_mass_g, na.rm = TRUE)
  ) %>%
  knitr::kable()
```

## Penguin Size vs Mass by Species

```{r}
df %>%
  filter(!is.na(bill_length_mm), !is.na(body_mass_g), 
         is.finite(bill_length_mm), is.finite(body_mass_g)) %>%
  ggplot(aes(x = bill_length_mm, y = body_mass_g, color = species)) +
  geom_point() + 
  geom_smooth(method = "lm")
```

```{r}
#library(DBI)
#library(duckdb)
#con <- DBI::dbConnect(duckdb::duckdb(), dbdir = "my-db.duckdb")
#DBI::dbWriteTable(con, "penguins", palmerpenguins::penguins)
#DBI::dbDisconnect(con, shutdown = TRUE)
```
